
#### Data

This data shows the average exercise rates by gender and work status at state(s) level in the United States (USA).The dataset has been obtained from `tidytuesday`,in which the link of the data can be obtained [here](https://github.com/rfordatascience/tidytuesday/blob/master/data/2018/2018-07-17/week16_exercise.xlsx).  

#### Purpose

The purpose of the app is to:

1. let the user to guess which demographic (i.e. gender and work status) and which states in the USA exercises more and reveal the statistics, 
2. allow user to choose a topic of interest (gender or workstatus) to further analyse on the average exercise rate in each state as compared to other state(s) chosen in the United States by using visual cues or representations (i.e. map of USA),
3. Interactively show how the different plot choices by further clicking to show the bar graph comparisons on demographics on the state(s) levels, which make data easier to understand and display comparisons clearly. 

There are a few aspects demonstrated by this app. Firstly, the second tab, "Fact Questions" let users to guess which demographic exercises more in the USA, and with the statistics revealed, these prompt self reflection to the user on their personal exercise rate.  The third tab, "Demographics" - users are able to personalise their view of data as they are able to choose their topic of interest (i.e. gender and work status), choose which states they want to see and choose whether they want to see the bar graph comparison of the data by further clicking on another button. The app also makes it easier for the users to digest the data by using visual cues/representations (i.e. map of USA) and colourful bar graphs to aid them in comparing the rate of exercise for each demographic. Overall, this makes learning aspects of data a fun and playful experience by using an interactive approach to see how the choices in demographics, states and plot types (ie. map or bar graphs) effect the visibility of these features.  



#### Creator

Min Min Soh (mmsoh1@student.monash.edu)

<details>
<summary>Session information</summary>
```{r, echo = FALSE}
sessioninfo::session_info()
```
</details>
